name: Deployment DEV

on: 
   push:
      branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -t minhaimage:$hashdocommit
      - name: lista images docker
        run: docker images
